# Dataset info
dataset: 'ds005841'
subjects: ['001', '002']
tasks: ['lumfront', 'lumperp']

# Save folders
save_dir: outputs
save_plot_dir: data/plots

# Data paths
target_dir: data/raw
processed_dir: data/processed
